## World
world:
  # Rendering must be on for semantic segmentation output
  no_rendering: False
  
  # Synchronous mode and the simulation time step (must be <= 0.1 sec for simulation fidelity)
  sync_mode: True
  delta_seconds: 0.1  # seconds per tick
  
  # Built-in map
  map: Town03
  
  # Carla weathers (in alphabetic order)
  # 0 - ClearNoon
  # 1 - ClearSunset
  # 2 - CloudyNoon
  # 3 - CloudySunset
  # 4 - Default
  # 5 - HardRainNoon
  # 6 - HardRainSunset
  # 7 - MidRainSunset
  # 8 - MidRainyNoon
  # 9 - SoftRainNoon
  # 10 - SoftRainSunset
  # 11 - WetCloudyNoon
  # 12 - WetCloudySunset
  # 13 - WetNoon
  # 14 - WetSunset
  weather: 4

## Autopilot
autopilot:
  auto_lane_change: True
  ignore_lights_percentage: 100
  vehicle_percentage_speed_difference: 0    # When set to negative, vehicles move beyond the speed limit

## Ego Vehicle
ego_veh:
  # Carla uses center of gravity as the model's origin
  # The following is roughly measured from Carla's Mustang model
  # Carla's Mustang:
  #   CG to rear axle: 1.4
  #   CG to front bumper: 2.4   
  raxle_to_fbumper: 3.8    # (m) Distance from rear axle to front bumper


## Sensors
sensor:
  # Ref: https://carla.readthedocs.io/en/0.9.9/ref_sensors/
  gnss:
    noise_alt_bias: '0.0'    # Mean parameter in the noise model for altitude.
    noise_alt_stddev: '0.0'  # Standard deviation parameter in the noise model for altitude.
    noise_lat_bias: '0.0'    # Mean parameter in the noise model for latitude.
    noise_lat_stddev: '0.0'  # Standard deviation parameter in the noise model for latitude.
    noise_lon_bias: '0.0'    # Mean parameter in the noise model for longitude.
    noise_lon_stddev: '0.0'  # Standard deviation parameter in the noise model for longitude.
  imu:
    noise_accel_stddev_x: '0.0'  # Standard deviation parameter in the noise model for acceleration (X axis).
    noise_accel_stddev_y: '0.0'  # Standard deviation parameter in the noise model for acceleration (Y axis).
    noise_accel_stddev_z: '0.0'  # Standard deviation parameter in the noise model for acceleration (Z axis).
    noise_gyro_bias_x: '0.0'     # Mean parameter in the noise model for the gyroscope (X axis).
    noise_gyro_bias_y: '0.0'     # Mean parameter in the noise model for the gyroscope (Y axis).
    noise_gyro_bias_z: '0.0'     # Mean parameter in the noise model for the gyroscope (Z axis).
    noise_gyro_stddev_x: '0.0'   # Standard deviation parameter in the noise model for the gyroscope (X axis).
    noise_gyro_stddev_y: '0.0'   # Standard deviation parameter in the noise model for the gyroscope (Y axis).
    noise_gyro_stddev_z: '0.0'   # Standard deviation parameter in the noise model for the gyroscope (Z axis).
  semantic_image:
    # Semantic segmentation image
    res_x: '800'  # px
    res_y: '600'  # px
    fov: '60'     # deg
  virtual_odom:
    noise_vx_bias: 0.0    # (m/s) Mean in the noise model for vx
    noise_vy_bias: 0.0    # (m/s) Mean in the noise model for vx
    noise_yaw_rate_bias: 0.0    # (deg) Mean in the noise model for yaw rate
    noise_vx_stddev: 0.0    # (m/s) Standard deviation in the noise model for vx
    noise_vy_stddev: 0.0    # (m/s) Standard deviation in the noise model for vy
    noise_yaw_rate_stddev: 0.0    # (deg) Standard deviation in the noise model for yaw_rate

## Setups
sim_duration: 180  # sec
recording: False