## World
world:
  # Rendering must be on for semantic segmentation
  no_rendering: False

  # Synchronous mode and the simulation time step (must be <= 0.1 sec for simulation fidelity)
  sync_mode: True
  delta_seconds: 0.1

  # Built-in map
  map: Town03

  # Carla weathers (in alphabetic order)
  # 0 - ClearNoon
  # 1 - ClearSunset
  # 2 - CloudyNoon
  # 3 - CloudySunset
  # 4 - Default
  # 5 - HardRainNoon
  # 6 - HardRainSunset
  # 7 - MidRainSunset
  # 8 - MidRainyNoon
  # 9 - SoftRainNoon
  # 10 - SoftRainSunset
  # 11 - WetCloudyNoon
  # 12 - WetCloudySunset
  # 13 - WetNoon
  # 14 - WetSunset
  weather: 4

## Autopilot

## Sensors
sensor:
  # Semantic segmentation image
  res_x: 800  # px
  res_y: 600  # px
  fov: 60     # deg

## Setups
sim_duration: 20  # sec
recording: False